libdigidocpp: digidoc Namespace Reference
digidoc Namespace Reference
Classes
class Conf
Configuration class which can reimplemented and virtual methods overloaded.
class ConfV2
Verison 2 of configuration class to add additonial parameters.
class ConfV3
Verison 3 of configuration class to add additonial parameters.
class Container
Offers functionality for handling data files and signatures in a container.
class DataFile
Data file wrapper providing methods for handling signed files or files to be signed in Container.
class DataFilePrivate
class Exception
Base exception class of the digidoc implementation.
class PKCS11Signer
Implements Signer interface for ID-Cards, which support PKCS#11 protocol.
class PKCS12Signer
Implements Signer interface for PKCS#12 files.
class Signature
Signature interface. Provides interface for handling a signature and the corresponding OCSP response properties.
class Signer
Signer interface. Provides interface for signing documents.
class WinSigner
Implements Signer interface for Windows Crypto backends.
class X509Cert
Wrapper for OpenSSL X509 certificate structure.
class XmlConf
XML Configuration class.
class XmlConfV2
Version 2 of XML Configuration class.
class XmlConfV3
Typedefs
using ConfCurrent = ConfV3
using initCallBack = void(*)(const Exception *e)
using XmlConfCurrent = XmlConfV3
Functions
DIGIDOCPP_EXPORT std::string appInfo ()
DIGIDOCPP_EXPORT void initialize (const std::string &appInfo="libdigidocpp", initCallBack callBack=nullptr)
DIGIDOCPP_EXPORT void terminate ()
DIGIDOCPP_EXPORT std::string version ()
Typedef Documentation
ConfCurrent
using digidoc::ConfCurrent = typedef ConfV3
initCallBack
using digidoc::initCallBack = typedef void (*)(const Exception *e)
XmlConfCurrent
using digidoc::XmlConfCurrent = typedef XmlConfV3
Function Documentation
appInfo()
string digidoc::appInfo ()
Returns registered application name
Referenced by initialize().
initialize()
void digidoc::initialize (const std::string & appInfo = "libdigidocpp", initCallBack callBack = nullptr)
Libdigidocpp’s initialization method: initializes dependent libraries, loads configuration settings from default configuration files (see Configuring Libdigidocpp) and initializes certificate store using TSL lists
Parameters
appInfo Application name for user agent string
callBack Callback when background thread TSL loading is completed
References appInfo(), digidoc::Conf::init(), and digidoc::Conf::instance().
terminate()
void digidoc::terminate ()
The termination method closes libraries used in Libdigidocpp implementation and deletes temporary files that may have been written to disk when working with the library.
References digidoc::Conf::init().
version()
string digidoc::version ()
Returns libdigidocpp library version